from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    current_date,
    lit,
    when,
    try_to_date,
    trim,
    concat_ws,
    sum as spark_sum,
    count,
)
from pyspark.sql.window import Window


# ============================================================
# SPARK SESSION
# ============================================================

spark = (
    SparkSession.builder
    .appName("UrbanCart-Products-PySpark")
    .master("local[*]")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/home/vrual/UrbanCart-AWS-Data-Engineering"
)

RAW_PATH = str(
    PROJECT_ROOT / "data/raw/products.parquet"
)

BRONZE_PATH = str(
    PROJECT_ROOT / "data/bronze/pyspark/products"
)

SILVER_PATH = str(
    PROJECT_ROOT / "data/silver/pyspark/products"
)

DQ_PATH = str(
    PROJECT_ROOT / "data/dq/pyspark/products"
)


# ============================================================
# LOAD RAW PRODUCT DATA
# ============================================================

df = spark.read.parquet(RAW_PATH)

print()
print("========================================")
print("RAW PRODUCT DATA")
print("========================================")

print("Rows:", df.count())
print("Columns:", len(df.columns))
print("Column names:", df.columns)


# ============================================================
# REMOVE EXISTING DQ COLUMN
# ============================================================
# The raw dataset was previously generated using the Pandas
# pipeline and therefore contains _dq_issue.
#
# For this PySpark pipeline, DQ must be generated by Spark itself.

if "_dq_issue" in df.columns:
    df = df.drop("_dq_issue")


# ============================================================
# SCHEMA
# ============================================================

print()
print("Schema:")

df.printSchema()


# ============================================================
# SAMPLE DATA
# ============================================================

print()
print("Sample records:")

df.show(
    10,
    truncate=False
)


# ============================================================
# WRITE BRONZE
# ============================================================

(
    df.write
    .mode("overwrite")
    .parquet(BRONZE_PATH)
)

print()
print("PySpark Bronze product data written successfully")


# ============================================================
# PRODUCT DATA QUALITY VALIDATION
# ============================================================

print()
print("========================================")
print("PRODUCT DATA QUALITY VALIDATION")
print("========================================")


# ============================================================
# DATE PARSING
# ============================================================
# try_to_date prevents malformed dates from crashing the job.
#
# Example:
# 2025-10-30 -> valid
# 30/10/2022 -> NULL -> DQ
#
# The source data is intentionally not modified.

df = df.withColumn(
    "created_date_parsed",
    try_to_date(
        trim(col("created_date")),
        "yyyy-MM-dd"
    )
)


# ============================================================
# DUPLICATE PRODUCT ID DETECTION
# ============================================================
# Use a Spark Window instead of collect().
# This is more scalable and appropriate for distributed data.

product_window = Window.partitionBy("product_id")

df = df.withColumn(
    "product_id_count",
    count("product_id").over(product_window)
)


# ============================================================
# DQ VALIDATION FLAGS
# ============================================================

df = (

    df

    # --------------------------------------------------------
    # Product ID
    # --------------------------------------------------------

    .withColumn(
        "dq_missing_product_id",
        col("product_id").isNull()
        | (trim(col("product_id")) == "")
    )

    .withColumn(
        "dq_duplicate_product_id",
        col("product_id_count") > 1
    )

    # --------------------------------------------------------
    # Seller ID
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_seller_id",
        col("seller_id").isNull()
        | (trim(col("seller_id")) == "")
        | (~trim(col("seller_id")).rlike("^S[0-9]{5}$"))
    )

    # --------------------------------------------------------
    # Product Name
    # --------------------------------------------------------

    .withColumn(
        "dq_missing_product_name",
        col("product_name").isNull()
        | (trim(col("product_name")) == "")
    )

    # --------------------------------------------------------
    # Category
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_category",
        col("category").isNull()
        | (trim(col("category")) == "")
    )

    # --------------------------------------------------------
    # Subcategory
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_subcategory",
        col("subcategory").isNull()
        | (trim(col("subcategory")) == "")
    )

    # --------------------------------------------------------
    # Unit Price
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_unit_price",
        col("unit_price").isNull()
        | (col("unit_price") <= 0)
    )

    # --------------------------------------------------------
    # Cost Price
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_cost_price",
        col("cost_price").isNull()
        | (col("cost_price") < 0)
        | (col("cost_price") > col("unit_price"))
    )

    # --------------------------------------------------------
    # Stock Quantity
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_stock_quantity",
        col("stock_quantity").isNull()
        | (col("stock_quantity") < 0)
    )

    # --------------------------------------------------------
    # Product Status
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_product_status",
        col("product_status").isNull()
        | (
            ~col("product_status").isin(
                "Active",
                "Inactive",
                "Discontinued"
            )
        )
    )

    # --------------------------------------------------------
    # Created Date
    # --------------------------------------------------------

    .withColumn(
        "dq_invalid_created_date",
        col("created_date_parsed").isNull()
    )

    # --------------------------------------------------------
    # Future Created Date
    # --------------------------------------------------------

    .withColumn(
        "dq_future_created_date",
        col("created_date_parsed") > current_date()
    )
)


# ============================================================
# BUILD DQ ISSUE COLUMN
# ============================================================
# concat_ws allows a record to have multiple DQ issues.
#
# Example:
# invalid_unit_price|invalid_cost_price

df = df.withColumn(
    "_dq_issue",
    concat_ws(
        "|",

        when(
            col("dq_missing_product_id"),
            lit("missing_product_id")
        ),

        when(
            col("dq_duplicate_product_id"),
            lit("duplicate_product_id")
        ),

        when(
            col("dq_invalid_seller_id"),
            lit("invalid_seller_id")
        ),

        when(
            col("dq_missing_product_name"),
            lit("missing_product_name")
        ),

        when(
            col("dq_invalid_category"),
            lit("invalid_category")
        ),

        when(
            col("dq_invalid_subcategory"),
            lit("invalid_subcategory")
        ),

        when(
            col("dq_invalid_unit_price"),
            lit("invalid_unit_price")
        ),

        when(
            col("dq_invalid_cost_price"),
            lit("invalid_cost_price")
        ),

        when(
            col("dq_invalid_stock_quantity"),
            lit("invalid_stock_quantity")
        ),

        when(
            col("dq_invalid_product_status"),
            lit("invalid_product_status")
        ),

        when(
            col("dq_invalid_created_date"),
            lit("invalid_created_date")
        ),

        when(
            col("dq_future_created_date"),
            lit("future_created_date")
        )
    )
)


# ============================================================
# SPLIT SILVER AND DQ
# ============================================================

dq_df = df.filter(
    col("_dq_issue") != ""
)

silver_df = df.filter(
    col("_dq_issue") == ""
)


# ============================================================
# DROP DQ HELPER COLUMNS
# ============================================================

dq_helper_columns = [
    "created_date_parsed",
    "product_id_count",

    "dq_missing_product_id",
    "dq_duplicate_product_id",
    "dq_invalid_seller_id",
    "dq_missing_product_name",
    "dq_invalid_category",
    "dq_invalid_subcategory",
    "dq_invalid_unit_price",
    "dq_invalid_cost_price",
    "dq_invalid_stock_quantity",
    "dq_invalid_product_status",
    "dq_invalid_created_date",
    "dq_future_created_date",
]


# Silver must contain clean business columns only.

silver_df = silver_df.drop(
    *dq_helper_columns,
    "_dq_issue"
)


# DQ keeps _dq_issue for investigation.

dq_df = dq_df.drop(
    *dq_helper_columns
)


# ============================================================
# DATA QUALITY SUMMARY
# ============================================================

total_records = df.count()

silver_records = silver_df.count()

dq_records = dq_df.count()


print()
print("========================================")
print("PRODUCT DATA QUALITY SUMMARY")
print("========================================")

print(
    "Total records:",
    total_records
)

print(
    "Valid records:",
    silver_records
)

print(
    "Invalid records:",
    dq_records
)


# ============================================================
# DQ ISSUE DISTRIBUTION
# ============================================================

print()
print("DQ issue distribution:")

(
    dq_df
    .select("_dq_issue")
    .groupBy("_dq_issue")
    .count()
    .orderBy(
        col("count").desc()
    )
    .show(
        truncate=False
    )
)


# ============================================================
# WRITE SILVER
# ============================================================

(
    silver_df.write
    .mode("overwrite")
    .parquet(SILVER_PATH)
)


# ============================================================
# WRITE DQ
# ============================================================

(
    dq_df.write
    .mode("overwrite")
    .parquet(DQ_PATH)
)


print()
print("========================================")
print("PRODUCT SILVER / DQ OUTPUT")
print("========================================")

print(
    "Silver rows:",
    silver_records
)

print(
    "Silver columns:",
    len(silver_df.columns)
)

print(
    "DQ rows:",
    dq_records
)

print(
    "DQ columns:",
    len(dq_df.columns)
)


# ============================================================
# FINAL VALIDATION
# ============================================================

print()
print("========================================")
print("FINAL PRODUCT VALIDATION")
print("========================================")


# ------------------------------------------------------------
# Duplicate Product IDs in Silver
# ------------------------------------------------------------

silver_duplicate_count = (
    silver_df
    .groupBy("product_id")
    .count()
    .filter(
        col("count") > 1
    )
    .count()
)

print(
    "Silver duplicate product IDs:",
    silver_duplicate_count
)


# ------------------------------------------------------------
# Silver Null Validation
# ------------------------------------------------------------

print()
print("Silver null values:")

silver_df.select(
    [
        spark_sum(
            col(c).isNull().cast("int")
        ).alias(c)
        for c in silver_df.columns
    ]
).show()


# ------------------------------------------------------------
# DQ Column Validation
# ------------------------------------------------------------

print(
    "_dq_issue present in Silver:",
    "_dq_issue" in silver_df.columns
)

print(
    "_dq_issue present in DQ:",
    "_dq_issue" in dq_df.columns
)


# ------------------------------------------------------------
# DQ Issue Null Validation
# ------------------------------------------------------------

dq_issue_null_count = (
    dq_df
    .filter(
        col("_dq_issue").isNull()
    )
    .count()
)

print(
    "DQ issue null values:",
    dq_issue_null_count
)


# ============================================================
# FINAL SUCCESS MESSAGE
# ============================================================

print()
print(
    "Product Silver and DQ data written successfully"
)


# ============================================================
# STOP SPARK
# ============================================================

spark.stop()